language: bash
dist: xenial

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: y
    - SNAPCRAFT_ENABLE_DEVELOPER_DEBUG: n

addons:
  snaps:
    - name: snapcraft
      channel: candidate
      classic: true
    - name: http
    - name: transfer
    - name: lxd
      channel: stable

script:
  - sudo apt update
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
  - sudo snapcraft --use-lxd
after_success:
  - cp *.snap "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
  - timeout 180 /snap/bin/transfer "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_failure:
  - sudo journalctl -u snapd
  - http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16