name: slack-term
summary: Slack client for your terminal
description: |
  A Slack client for your terminal.
  * Get a slack token from https://api.slack.com/docs/oauth-test-tokens
  * Create $HOME/snap/slack-term/current/slack-term.json
  * Contents detailed at https://github.com/erroneousboat/slack-term
  * slack-term --config $HOME/snap/slack-term/current/slack-term.json
adopt-info: slack-term

grade: stable
confinement: strict

apps:
  slack-term:
    command: slack-term
    plugs:
      - network
      - home

parts:
  go:
    source-tag: go1.10.4
  slack-term:
    after: [go]
    source: https://github.com/erroneousboat/slack-term.git
    plugin: go
    go-importpath: github.com/erroneousboat/slack-term
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info slack-term | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        # XXX The snapcraft go plugin builds a link to the src dir, not to the
        # build dir. That might be a bug, but let's better checkout both to be
        # safe that we are not building the wrong thing. --elopio - 20171108
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags)"
